# Generated by Django 3.2.4 on 2021-07-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='private_key',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='public_key',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='private_key',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='public_key',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
