# Generated by Django 3.2.4 on 2021-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20210702_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='wallet_address',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='wallet_address',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
