# Generated by Django 3.2.4 on 2021-07-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20210703_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='wallet_address',
        ),
    ]
