# Generated by Django 3.2.4 on 2021-07-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_auto_20210718_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
