# Generated by Django 3.2.4 on 2021-07-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_alter_doctor_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='profile',
            new_name='user',
        ),
    ]
