# Generated by Django 3.2.4 on 2021-07-21 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0035_auto_20210721_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile',
        ),
        migrations.AddField(
            model_name='doctor',
            name='identity',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='identity',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
