# Generated by Django 3.2.4 on 2021-08-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0037_auto_20210721_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='pb_key',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pb_key',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
