# Generated by Django 3.2.4 on 2021-08-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom_jeune_fille',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='situation_F',
            field=models.CharField(max_length=40),
        ),
    ]
