# Generated by Django 3.2.4 on 2021-08-07 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0042_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='brth_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
