# Generated by Django 3.2.4 on 2021-08-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0045_remove_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='brth_day',
        ),
    ]
