# Generated by Django 3.2.4 on 2021-08-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0046_remove_patient_brth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
    ]
