# Generated by Django 3.2.4 on 2021-08-07 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0047_remove_patient_assigneddoctorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='brth_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
