# Generated by Django 3.2.4 on 2021-08-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0048_auto_20210807_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='brth_day',
        ),
    ]
