# Generated by Django 3.2.4 on 2021-08-08 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0049_remove_patient_brth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='brth_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
