# Generated by Django 3.2.4 on 2021-08-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0053_patient_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
