# Generated by Django 3.2.4 on 2021-08-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0054_remove_patient_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
