# Generated by Django 3.2.4 on 2021-08-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0055_patient_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('documentType', models.CharField(choices=[('Prescription', 'Prescription'), ('Radiology', 'Radiology'), ('Analyse', 'Analyse'), ('Comment', 'Comment')], default='Prescription', max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=40, null=True)),
                ('traitement', models.CharField(max_length=40, null=True)),
                ('boite', models.PositiveIntegerField(null=True)),
                ('medicament2', models.CharField(max_length=40, null=True)),
                ('traitement2', models.CharField(max_length=40, null=True)),
                ('boite2', models.PositiveIntegerField(null=True)),
                ('medicament3', models.CharField(max_length=40, null=True)),
                ('traitement3', models.CharField(max_length=40, null=True)),
                ('boite3', models.PositiveIntegerField(null=True)),
                ('medicament4', models.CharField(max_length=40, null=True)),
                ('traitement4', models.CharField(max_length=40, null=True)),
                ('boite4', models.PositiveIntegerField(null=True)),
                ('medicament5', models.CharField(max_length=40, null=True)),
                ('traitement5', models.CharField(max_length=40, null=True)),
                ('boite5', models.PositiveIntegerField(null=True)),
                ('medicament6', models.CharField(max_length=40, null=True)),
                ('traitement6', models.CharField(max_length=40, null=True)),
                ('boite6', models.PositiveIntegerField(null=True)),
                ('medicament7', models.CharField(max_length=40, null=True)),
                ('traitement7', models.CharField(max_length=40, null=True)),
                ('boite7', models.PositiveIntegerField(null=True)),
                ('medicament8', models.CharField(max_length=40, null=True)),
                ('traitement8', models.CharField(max_length=40, null=True)),
                ('boite8', models.PositiveIntegerField(null=True)),
                ('medicament9', models.CharField(max_length=40, null=True)),
                ('traitement9', models.CharField(max_length=40, null=True)),
                ('boite9', models.PositiveIntegerField(null=True)),
                ('medicament10', models.CharField(max_length=40, null=True)),
                ('traitement10', models.CharField(max_length=40, null=True)),
                ('boite10', models.PositiveIntegerField(null=True)),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.document')),
            ],
        ),
    ]
